source 'https://rubygems.org'

ruby '>= 3.1.0'

gem 'rails', '~> 7.2.2'
gem 'puma', '~> 6.5'

# Database
gem 'sqlite3', '~> 2.6'
gem 'mysql2', '~> 0.5.6'

# Asset pipeline
gem 'sprockets-rails', '~> 3.5'
gem 'sassc-rails', '~> 2.1'
gem 'terser', '~> 1.2'
gem 'importmap-rails', '~> 2.1'

# JavaScript
gem 'jquery-rails', '~> 4.6'

# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1'

# Use Jbuilder for JSON APIs
# gem 'jbuilder', '~> 2.12'
